---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: molecule_php_instance
    dockerfile: Dockerfile.j2
    image: debian:10-slim
lint: |
  set -e
  printf "##########################################\n"
  printf "# Performing yamllint \n"
  yamllint -c ./molecule/lint_config/config.yml .
  printf "##########################################\n"
  printf "# Performing ansible-lint \n"
  ansible-lint -c ./molecule/lint_config/ansible-lint.yml .
provisioner:
  name: ansible
verifier:
  name: ansible
