---
- name: check_os | check compatibility
  fail:
    msg: Your OS {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported
  when:
    - (ansible_distribution != 'Debian' and ansible_distribution_major_version|int < 10)
    - (ansible_distribution != 'Rocky' and ansible_distribution_major_version|int < 8)
    - (ansible_distribution != 'RedHat' and ansible_distribution_major_version|int < 8)
    - (ansible_distribution != 'CentOS' and ansible_distribution_major_version|int != 7)

- name: use python3 package
  block:
    - name: check_os | ensure python3 is installed
      package:
        state: present
        name: python3
      become: yes
      become_user: 'root'
      become_method: su

    - name: check_os | setup python3 interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
  when:
    - ansible_distribution == 'Debian' or
      ansible_distribution == 'Rocky' or
      (ansible_distribution == 'RedHat' and ansible_distribution_major_version|int > 7)

- name: check_os | setup python2 interpreter
  set_fact:
    ansible_python_interpreter: /usr/bin/python
  when:
    - (ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7)
